# Generated by Django 5.0.7 on 2024-07-20 00:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("savings", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="savingsgoal",
            name="created_at",
        ),
        migrations.AlterField(
            model_name="savingsgoal",
            name="name",
            field=models.CharField(max_length=255),
        ),
    ]
