# Generated by Django 5.0.7 on 2024-07-20 11:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("savings", "0002_remove_savingsgoal_created_at_alter_savingsgoal_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="contribution",
            name="user",
        ),
        migrations.AlterField(
            model_name="contribution",
            name="goal",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="contributions",
                to="savings.savingsgoal",
            ),
        ),
        migrations.AlterField(
            model_name="savingsgoal",
            name="name",
            field=models.CharField(max_length=100),
        ),
    ]
