# Generated by Django 5.0.7 on 2024-07-20 16:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("savings", "0003_remove_contribution_user_alter_contribution_goal_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="savingsgoal",
            name="user",
        ),
        migrations.AddField(
            model_name="savingsgoal",
            name="total_contributed",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
