# Generated by Django 5.0.7 on 2024-07-23 14:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("savings", "0007_savingsgoal_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="savingsgoal",
            name="name",
            field=models.CharField(max_length=100),
        ),
    ]
