# Generated by Django 5.0.7 on 2024-07-23 16:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("savings", "0008_alter_savingsgoal_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="savingsgoal",
            name="progress_percentage",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name="savingsgoal",
            name="remaining_amount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
