# Generated by Django 5.0.7 on 2024-07-24 09:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("savings", "0009_savingsgoal_progress_percentage_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="savingsgoal",
            name="progress_percentage",
        ),
        migrations.RemoveField(
            model_name="savingsgoal",
            name="remaining_amount",
        ),
        migrations.AddField(
            model_name="contribution",
            name="income",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name="savingsgoal",
            name="status",
            field=models.CharField(
                choices=[("completed", "Completed"), ("in_progress", "In Progress")],
                default=0,
                max_length=20,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="savingsgoal",
            name="name",
            field=models.CharField(max_length=255),
        ),
    ]
