# Generated by Django 5.0.7 on 2024-07-24 10:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("savings", "0011_remove_contribution_income_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="insight",
            name="goal",
        ),
        migrations.RemoveField(
            model_name="insight",
            name="user",
        ),
        migrations.RemoveField(
            model_name="savingscontribution",
            name="status",
        ),
        migrations.RemoveField(
            model_name="savingsgoal",
            name="status",
        ),
        migrations.CreateModel(
            name="SavingsInsights",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "total_savings",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                (
                    "average_contribution",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                ("contribution_frequency", models.DurationField()),
                (
                    "goal_progress",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
                ),
                ("tips", models.TextField(blank=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="Goal",
        ),
        migrations.DeleteModel(
            name="Insight",
        ),
    ]
