# Generated by Django 5.0.7 on 2024-07-24 15:30

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("savings", "0012_remove_insight_goal_remove_insight_user_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="savingsgoal",
            name="total_contributed",
        ),
    ]
